# Generated by Django 4.2.23 on 2025-07-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate',
            new_name='rating',
        ),
    ]
